GreenWebsite/GreenWebsite/Controllers/ImageGalleriesController.cs
using System;
using System.Collections.Generic;

using System.IO;
using System.Linq;

using System.Web;
using System.Web.Mvc;
using GreenWebsite.DAL;
using GreenWebsite.DAL.security;
using GreenWebsite.Models;


namespace GreenWebsite.Controllers
{
    //[CustomAuthorize(RolesConfigKey = "RolesConfigKey")]
    // [CustomAuthorize(UsersConfigKey = "UsersConfigKey")]
    [CustomAuthorize(Roles = "Admin")]
    // [CustomAuthorize(Users = "1")]
    public class ImageGalleriesController : Controller
    {
        private GreenContext db = new GreenContext();

        public ActionResult Index()
        {
            var imagesModel = new ImageGallery();
            var imageFiles = Directory.GetFiles(Server.MapPath("~/Upload_Images/"));
            foreach (var item in imageFiles)
            {
                imagesModel.ImageList.Add(Path.GetFileName(item));
            }
            return View(imagesModel);
        }
    
        [HttpGet]
        public ActionResult UploadImage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UploadImageMethod()
        {
            if (Request.Files.Count != 0)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    int fileSize = file.ContentLength;
                    string fileName = file.FileName;
                    try
                    {
                        file.SaveAs(Server.MapPath("~/Upload_Images/" + fileName));
                        ImageGallery imageGallery = new ImageGallery();
                        imageGallery.ID = Guid.NewGuid();
                        imageGallery.Name = fileName;
                        imageGallery.ImagePath = "~/Upload_Images/" + fileName;
                        db.ImageGallery.Add(imageGallery);
                        db.SaveChanges();
                    }
                    catch(Exception e)
                    {
                        return View("Index");
                    }
                }
                return Content("Success");
            }
            return Content("failed");
        }
    }
}

GreenWebsite/GreenWebsite/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using GreenWebsite.DAL;
using GreenWebsite.DAL.security;
using GreenWebsite.Models;
using WebMatrix.WebData;

namespace GreenWebsite.Controllers
{ //[CustomAuthorize(RolesConfigKey = "RolesConfigKey")]
    // [CustomAuthorize(UsersConfigKey = "UsersConfigKey")]
    [CustomAuthorize(Roles = "Admin")]
    // [CustomAuthorize(Users = "1")]
    public class SupportController : Controller
    {
        private GreenContext db = new GreenContext();

        public ActionResult Index()
        {
            return View(db.Supports.ToList());
        }

        //
        // GET: /Support/Create

        public ActionResult Create()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Support support)
        {
            if (ModelState.IsValid)
            {
                List<FileDetail> fileDetails = new List<FileDetail>();
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        FileDetail fileDetail = new FileDetail()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid()
                        };
                        fileDetails.Add(fileDetail);

                        var path = Path.Combine(Server.MapPath("~/Upload_Files"), fileDetail.Id + fileDetail.Extension);
                        file.SaveAs(path);
                    }
                }

                support.FileDetails = fileDetails;
                db.Supports.Add(support);
                db.SaveChanges(WebSecurity.CurrentUserName);
                return RedirectToAction("Index");
            }

            return View(support);
        }

        //
        // GET: /Support/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Support support = db.Supports.Include(s => s.FileDetails).SingleOrDefault(x => x.SupportId == id);
            if (support == null)
            {
                return HttpNotFound();
            }
            return View(support);
        }


        public FileResult Download(String p, String d)
        {
            return File(Path.Combine(Server.MapPath("~/Upload_Files"), p), System.Net.Mime.MediaTypeNames.Application.Octet, d);
        }



        //
        // POST: /Support/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Support support)
        {
            if (ModelState.IsValid)
            {

                //New Files
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        FileDetail fileDetail = new FileDetail()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid(),
                            SupportId = support.SupportId
                        };
                        var path = Path.Combine(Server.MapPath("~/Upload_Files"), fileDetail.Id + fileDetail.Extension);
                        file.SaveAs(path);

                        db.Entry(fileDetail).State = EntityState.Added;
                    }
                }

                db.Entry(support).State = EntityState.Modified;
                db.SaveChanges(WebSecurity.CurrentUserName);
                return RedirectToAction("Index");
            }
            return View(support);
        }



        [HttpPost]
        public JsonResult DeleteFile(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Result = "Error" });
            }
            try
            {
                Guid guid = new Guid(id);
                FileDetail fileDetail = db.FileDetails.Find(guid);
                if (fileDetail == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }

                //Remove from database
                db.FileDetails.Remove(fileDetail);
                db.SaveChanges(WebSecurity.CurrentUserName);

                //Delete file from the file system
                var path = Path.Combine(Server.MapPath("~/Upload_Files"), fileDetail.Id + fileDetail.Extension);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }





        //
        // POST: /Support/Delete/5

        [HttpPost]
        public JsonResult Delete(int id)
        {
            try
            {
                Support support = db.Supports.Find(id);
                if (support == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }

                //delete files from the file system

                foreach (var item in support.FileDetails)
                {
                    String path = Path.Combine(Server.MapPath("~/Upload_Files"), item.Id + item.Extension);
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                }

                db.Supports.Remove(support);
                db.SaveChanges(WebSecurity.CurrentUserName);
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

    
    }
}

GreenWebsite/GreenWebsite/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using GreenWebsite.DAL;
using GreenWebsite.DAL.security;
using GreenWebsite.Models;
using PagedList;
using WebMatrix.WebData;

namespace GreenWebsite.Controllers
{  //[CustomAuthorize(RolesConfigKey = "RolesConfigKey")]
    // [CustomAuthorize(UsersConfigKey = "UsersConfigKey")]
    [CustomAuthorize(Roles = "Admin")]
    // [CustomAuthorize(Users = "1")]
    public class UsersController : Controller
    {
        private GreenContext db = new GreenContext();

        // GET: Users
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, string Date1String, string Date2String,
            int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.EmailSortParm = String.IsNullOrEmpty(sortOrder) ? "email" : "";

            string name = WebSecurity.CurrentUserName;
            var users = from s in db.Users
                        where s.Email != name
                       select s;

            if (searchString != null || (Date1String != null && Date2String != null))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s =>
                  s.Email.ToUpper().Contains(searchString.ToUpper())
                  ||
                  s.Email.ToUpper().Contains(searchString.ToUpper()));
            }

            else if (!String.IsNullOrEmpty(Date1String) && !String.IsNullOrEmpty(Date2String))
            {
                DateTime date = Convert.ToDateTime(Date1String);
                DateTime date2 = Convert.ToDateTime(Date2String);
                 users = from s in db.Users
                                where s.Email != name && date <= s.CreateDate && date2 >= s.CreateDate
                                select s;



            }
            switch (sortOrder)
            {
                case "name_desc":
                    users = users.OrderByDescending(s => s.Username);
                    break;

                case "Date":
                    users = users.OrderBy(s => s.CreateDate);
                    break;
                case "date_desc":
                    users = users.OrderByDescending(s => s.CreateDate);
                    break;
                default:
                    users = users.OrderBy(s => s.UserID);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(users.ToPagedList(pageNumber, pageSize));
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,Username,Email,Password,ConfirmPassword,FirstName,LastName,IsActive,CreateDate,memberNumber,IDNO")] User user)
        {
            if (ModelState.IsValid)
            {
                if (Request["Roles"] == "Admin")
                {
                    Role role1 = new Role { RoleName = "Admin" };

                    user.Roles = new List<Role>();
                    user.Roles.Add(role1);
                    user.memberNumber = "ADM:"+user.Email;
                }
                else if (Request["Roles"] == "User")
                {
                    Role role2 = new Role { RoleName = "User" };
                    user.Roles = new List<Role>();
                    user.Roles.Add(role2);
                }
                user.Password = Request["Password"].ToString();
                user.ConfirmPassword = Request["ConfirmPassword"].ToString();
                user.Password = ComputeHash(user.Password, new SHA256CryptoServiceProvider());
                user.ConfirmPassword = ComputeHash(user.ConfirmPassword, new SHA256CryptoServiceProvider());
                user.IsActive = true;
                user.CreateDate = DateTime.Now;
                db.Users.Add(user);
                db.SaveChanges(WebSecurity.CurrentUserName);
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            user.Password = "";
            user.ConfirmPassword = "";
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,Username,Email,Password,ConfirmPassword,FirstName,LastName,IsActive,CreateDate,memberNumber,IDNO")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Password = Request["Password"].ToString();
                user.ConfirmPassword = Request["ConfirmPassword"].ToString();
                user.Password = ComputeHash(user.Password, new SHA256CryptoServiceProvider());
                user.ConfirmPassword = ComputeHash(user.ConfirmPassword, new SHA256CryptoServiceProvider());
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges(WebSecurity.CurrentUserName);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges(WebSecurity.CurrentUserName);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //password  hashing function
        public string ComputeHash(string input, HashAlgorithm algorithm)
        {
            Byte[] inputBytes = Encoding.UTF8.GetBytes(input);

            Byte[] hashedBytes = algorithm.ComputeHash(inputBytes);

            return BitConverter.ToString(hashedBytes);
        }
    }
}

GreenWebsite/GreenWebsite/Views/Shared/AdminP.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Green Pastures</title>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link href="~/Content/dashboard.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <link href="Content/dashboard.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")

    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" id="MyNav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Green Pastures Dashboard :" + @User.Identity.Name, "Index", "Admin", null, new {@class = "navbar-brand"})

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav" id="MyLi">
                <li>@Html.ActionLink("Profile", "Index", "Users")</li>
                <li>@Html.ActionLink("File", "Index", "Support")</li>
                <li>@Html.ActionLink("Audit Log", "Index", "AuditLog")</li>
                <li>@Html.ActionLink("Audit Log Details", "Index", "AuditLogDetails")</li>
                <li>@Html.ActionLink("User Profile ", "Index", "AdminProfile")</li>


            </ul>
            <ul class="nav navbar-nav navbar-right">


                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "LogOut" ? "active" : "")">
                    @Html.ActionLink("LogOut", "LogOut", "Account", new {area = ""}, new {@class = "glyphicon glyphicon-log-out"})
                </li>
                <li><a href="~/Help/HTML/index.html" target="_blank"><span class="glyphicon glyphicon-question-sign"></span>Help</a></li>
            </ul>
        </div>

    </div>

</div>




<div class="container body-content">
    @RenderBody()
    <hr/>

</div>
</body>

<footer>


    <div class="row">

        <div class="col-md-4">

            <p style="color: black">
                <a class="btn btn-success" title="This section consists of committees such as Supervisory,Credit,Education and overall team management" style="color: white; background-color: darkgreen;" href="~/Home/About">Team Members &raquo;</a>
                <br/>
            </p>

        </div>
        <div class="col-md-4">
            <p style="color: black">
                <a class="btn btn-success" title="This section consists of Loans,Savings,Membership Shares and Additional Services" style="color: white; background-color: darkgreen;" href="~/Home/Products">Products &raquo;</a><br/>
            </p>
        </div>
        <div class="col-md-4">
            <p style="color: black">
                <a class="btn btn-success" title="This section consists of Geo-Location and contact details." style="color: white; background-color: darkgreen;" href="~/Home/Contact">Map-Location&raquo;</a><br/>

            </p>
        </div>





    </div>



    <a href="#"><img src="~/images/facebook.png" width="32" height="32"/></a>
    <a href="#"><img src="~/images/linkedin.png" width="32" height="32"/></a>
    <a href="#"><img src="~/images/twitter.png" width="32" height="32"/></a>
    <a href="https://play.google.com/store/apps/details?id=com.greenapiclient"><img src="~/images/playstore.png" width="32" height="32"/></a>
    <p style="color: white; font-size: 8pt">
        &copy; @DateTime.Now.Year - GREEN PASTURES SAVINGS & CREDIT CO-OPERATIVE SOCIETY


    </p>
    <p class="pull-right">
        <a id="myBack" class="btn btn-lg btn-success" href="#"><img src="~/images/up-arrow.png" width="32" height="32"/></a>
    </p>

</footer>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</html>

GreenWebsite/GreenWebsite/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <title>Green Pastures Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    
    <!-- Bootstrap core CSS -->
    <link href="Content/dashboard.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="assets/js/ie-emulation-modes-warning.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="MyNav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Green Pastures Dashboard :" + @User.Identity.Name, "Index", "Admin", null, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="MyLi">
                    <li >@Html.ActionLink("Profile", "Index", "Users")</li>
                    <li >@Html.ActionLink("File", "Index", "Support")</li>
                    <li>@Html.ActionLink("Audit Log", "Index", "AuditLog")</li>
                    <li>@Html.ActionLink("Audit Log Details", "Index", "AuditLogDetails")</li>
          <li>@Html.ActionLink("User Profile ", "Index", "AdminProfile")</li>
                   

                </ul>
                <ul class="nav navbar-nav navbar-right">

                  
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "LogOut" ? "active" : "")">
                        @Html.ActionLink("LogOut", "LogOut", "Account", new { area = "" }, new { @class = "glyphicon glyphicon-log-out" })
                    </li>
                    <li><a href="~/Help/HTML/index.html" target="_blank"><span class="glyphicon glyphicon-question-sign"></span>Help</a></li>
                </ul>
            </div>

        </div>
      
    </div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="#">@Html.ActionLink("Overview", "Index", "Admin")<span class="sr-only">(current)</span></a></li>

                <li>@Html.ActionLink("Document Records", "Index", "Support")</li>
                <li>@Html.ActionLink("Profile Accounts", "Index", "Users")</li>
                <li>@Html.ActionLink("Audit Log", "Index", "AuditLog")</li>
                <li>@Html.ActionLink("Events", "Index", "Events")</li>
                <li>@Html.ActionLink("Update Gallery", "Index", "ImageGalleries")</li>
                <li>@Html.ActionLink("ManageGallery", "Index", "ImageGalleries1")</li>
                <li>@Html.ActionLink("Audit Log Details", "Index", "AuditLogDetails")</li>
                <li>
                    @Html.ActionLink("LogOut", "LogOut", "Account", new { area = "" }, new { @class = "glyphicon glyphicon-user" })
            </li>

        </ul>

    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header" style="color: green">Administration Dashboard: @User.Identity.Name</h1>
        <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">

                <a href="~/Support/Index">
                    <img src="~/images/file_upload_image.png" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                </a>
                <span class="text-muted">@Html.ActionLink("Document Records", "Index", "Support")</span>
            </div>

            <div class="col-xs-6 col-sm-3 placeholder">
                <a href="~/Users/Index">
                    <img src="~/images/web-user.jpg" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    </a>
                    <span class="text-muted">@Html.ActionLink("Profile Accounts", "Index", "Users")</span>
</div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <a href="~/AuditLog/Index">
                    <img src="~/images/audit-trail.jpg" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    </a>
                    <span class="text-muted">@Html.ActionLink("AuditLog", "Index", "AuditLog")</span>
</div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <a href="~/AuditLogDetails/Index">
                    <img src="~/images/audit-trail.jpg" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    </a>
                    <span class="text-muted">@Html.ActionLink("AuditLog Details", "Index", "AuditLogDetails")</span>
</div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <a href="~/AdminProfile/Index">
                    <img src="~/images/web-user.jpg" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    </a>
                    <span class="text-muted">@Html.ActionLink("Profile:" + @User.Identity.Name, "Index", "AdminProfile")</span>
</div>
        </div>
        @RenderBody()
        <hr />
        <footer>






            <a href="#"><img src="~/images/facebook.png" width="32" height="32" /></a>
            <a href="#"><img src="~/images/linkedin.png" width="32" height="32" /></a>
            <a href="#"><img src="~/images/twitter.png" width="32" height="32" /></a>
            <p style="color: white;font-size:8pt">
                &copy; @DateTime.Now.Year - GREEN PASTURES SAVINGS & CREDIT CO-OPERATIVE SOCIETY


            </p>
            <p class="pull-right">
                <a id="myBack" class="btn btn-lg btn-success" href="#"><img src="~/images/up-arrow.png" width="32" height="32" /></a>
            </p>

        </footer>
    </div>
</div>
</div>
       
            <script src="~/Scripts/jquery-1.10.2.min.js"></script>
            <script src="~/Scripts/bootstrap.min.js"></script>
            
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    
            @RenderSection("scripts", required: false)
</body>
</html>