GreenWebsite/GreenWebsite/Controllers/AuditLogController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using GreenWebsite.DAL;
using GreenWebsite.DAL.security;
using PagedList;
using TrackerEnabledDbContext.Common.Models;

namespace GreenWebsite.Controllers
{    //[CustomAuthorize(RolesConfigKey = "RolesConfigKey")]
     // [CustomAuthorize(UsersConfigKey = "UsersConfigKey")]
    [CustomAuthorize(Roles = "Admin")]
    public class AuditLogController : Controller
    {
        private GreenContext db = new GreenContext();
        // GET: AuditLog
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, string Date1String, string Date2String,
            int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.EmailSortParm = String.IsNullOrEmpty(sortOrder) ? "email" : "";
            var audit = from s in db.AuditLog
                select s;
            if (searchString != null || (Date1String != null && Date2String != null))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
               audit = audit.Where(s =>
                 s.UserName.ToUpper().Contains(searchString.ToUpper())
                 ||
                 s.UserName.ToUpper().Contains(searchString.ToUpper()));
            }

            else if (!String.IsNullOrEmpty(Date1String) && !String.IsNullOrEmpty(Date2String))
            {
                DateTime date = Convert.ToDateTime(Date1String);
                DateTime date2 = Convert.ToDateTime(Date2String);
               audit = from s in db.AuditLog
                          
                             where date <= s.EventDateUTC && date2 >= s.EventDateUTC
                             select s;


            }
            switch (sortOrder)
            {
                case "name_desc":
                    audit = audit.OrderByDescending(s => s.UserName);
                    break;

                case "Date":
                    audit = audit.OrderBy(s => s.EventDateUTC);
                    break;
                case "date_desc":
                    audit = audit.OrderByDescending(s => s.EventDateUTC);
                    break;
                default:
                 audit = audit.OrderBy(s => s.AuditLogId);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View( audit.ToPagedList(pageNumber, pageSize));
        }

        // GET: AuditLog/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
          AuditLog audit = await db.AuditLog.FindAsync(id);
            if (audit == null)
            {
                return HttpNotFound();
            }
            return View(audit);
        }


        // POST: AuditLog/Create
       


        // GET: AdminShares/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
          AuditLog audit = await db.AuditLog.FindAsync(id);
            if (audit == null)
            {
                return HttpNotFound();
            }
            return View(audit);
        }

        // POST: AdminShares/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AuditLog audit = await db.AuditLog.FindAsync(id);
            db.AuditLog.Remove(audit);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GreenWebsite/GreenWebsite/Views/AuditLog/Delete.cshtml
@model TrackerEnabledDbContext.Common.Models.AuditLog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminP.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuditLogId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuditLogId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDateUTC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDateUTC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeFullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeFullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecordId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecordId)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GreenWebsite/GreenWebsite/Views/AuditLog/Details.cshtml
@model TrackerEnabledDbContext.Common.Models.AuditLog

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminP.cshtml";
}

<h2>Audit Log Details</h2>

<div>
  
    <h4>User:@User.Identity.Name</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.AuditLogId)
                </dt>

                <dd>
                    @Html.DisplayNameFor(model => model.AuditLogId)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UserName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EventDateUTC)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EventDateUTC)
                </dd>

                <dt>
                    Local Time
                </dt>

                <dd>

                    @DateTime.Parse(Html.DisplayFor(model => model.EventDateUTC).ToString()).ToLocalTime().ToString()

                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EventType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EventType)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TypeFullName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TypeFullName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RecordId)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RecordId)
                </dd>

            </dl>
</div>
<p>

    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
</p>

GreenWebsite/GreenWebsite/Views/AuditLog/Index.cshtml
@model PagedList.IPagedList<TrackerEnabledDbContext.Common.Models.AuditLog>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{

    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using (Html.BeginForm("Index", "AuditLog", FormMethod.Get))
{
    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-4">
              UserName: @Html.TextBox("SearchString", ViewBag.CurrentFilter as
                                 string)
             
            </div>
            <div class="col-md-4">
                <input type="submit" class="btn btn-success" value="Search" />
            </div>
            </div>
        <div class="form-group">
           <div class="col-md-4">
               Start Date : @Html.JQueryUI().Datepicker("Date1String")
            </div>
        </div>
        <div class="form-group">
        <div class="col-md-4">
            End.. Date : @Html.JQueryUI().Datepicker("Date2String")
            </div>
            <div class="col-md-4">

                <input type="submit" class="btn btn-success" value="Search" />
            </div>
        </div>
     

    </div>



}
<h3 style="color:green">Audit Log</h3>
<table class="table table-striped">
    <tr>

        <th>
            AuditLogId
        </th>
        <th>
            @Html.ActionLink("UserName", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("EventDateUTC", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })

            </th>
        <th>
            Event Date Local
        </th>
        <th>
            EventType
        </th>
        <th>
            TypeFullName
        </th>
        <th>
            RecordId
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AuditLogId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDateUTC)
            </td>
            <td>

                @DateTime.Parse(Html.DisplayFor(modelItem => item.EventDateUTC).ToString()).ToLocalTime().ToString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeFullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecordId)
            </td>

            <td>

                @Html.ActionLink("Details", "Details", new { id = item.AuditLogId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.AuditLogId })
            </td>
        </tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
@Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
new
{
    page,
    sortOrder = ViewBag.CurrentSort,
    currentFilter =
ViewBag.CurrentFilter
}))